/**
 * Cloudflare Access JWT verification tests (D-03, D-04).
 *
 * Exercises the pure `verifyAccessJwt` check and the `authenticateRequest`
 * middleware from `worker/src/auth.ts` with real RS256 tokens generated by
 * `crypto.subtle` inside the Workers runtime. Every rejection reason is
 * asserted exactly so the 401 envelope stays stable.
 */
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  authenticateRequest,
  createJwksCache,
  verifyAccessJwt,
  type JsonWebKeySet,
} from "../src/auth";

const TEAM_DOMAIN = "example.cloudflareaccess.com";
const ISSUER = `https://${TEAM_DOMAIN}`;
const AUDIENCE = "replace-with-access-application-aud";
/** Fixed "now" so every expiry/not-before assertion is deterministic. */
const NOW = Date.parse("2026-09-11T12:00:00.000Z");
const NOW_SECONDS = Math.floor(NOW / 1000);

function base64UrlEncode(input: string | Uint8Array | ArrayBuffer): string {
  const bytes =
    typeof input === "string"
      ? new TextEncoder().encode(input)
      : input instanceof Uint8Array
        ? input
        : new Uint8Array(input);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

interface TestSigner {
  jwks: JsonWebKeySet;
  sign: (claims: Record<string, unknown>) => Promise<string>;
}

/** Generate an RSA key pair and a signer that mints RS256 JWTs for it. */
async function createTestSigner(kid = "test-key-1"): Promise<TestSigner> {
  const keyPair = await crypto.subtle.generateKey(
    {
      name: "RSASSA-PKCS1-v1_5",
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["sign", "verify"]
  );
  const publicJwk = await crypto.subtle.exportKey("jwk", keyPair.publicKey);
  const jwks: JsonWebKeySet = {
    keys: [{ ...publicJwk, kid, alg: "RS256", use: "sig" }],
  };
  const sign = async (claims: Record<string, unknown>): Promise<string> => {
    const header = { alg: "RS256", kid, typ: "JWT" };
    const headerB64 = base64UrlEncode(JSON.stringify(header));
    const payloadB64 = base64UrlEncode(JSON.stringify(claims));
    const data = new TextEncoder().encode(`${headerB64}.${payloadB64}`);
    const signature = await crypto.subtle.sign(
      "RSASSA-PKCS1-v1_5",
      keyPair.privateKey,
      data
    );
    return `${headerB64}.${payloadB64}.${base64UrlEncode(signature)}`;
  };
  return { jwks, sign };
}

/** Default valid Access claims for the fixed test instant. */
function validClaims(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    iss: ISSUER,
    aud: AUDIENCE,
    exp: NOW_SECONDS + 3600,
    nbf: NOW_SECONDS - 60,
    email: "operator@hivarium.test",
    sub: "user_123",
    name: "Test Operator",
    ...overrides,
  };
}

describe("verifyAccessJwt", () => {
  it("accepts a valid Access JWT and derives the operator identity", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims());

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({
      ok: true,
      identity: {
        email: "operator@hivarium.test",
        sub: "user_123",
        name: "Test Operator",
      },
    });
  });

  it("rejects a token with a tampered signature", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims());
    const [header, payload] = token.split(".");
    const tampered = `${header}.${payload}.${base64UrlEncode("forged-signature")}`;

    const result = await verifyAccessJwt(tampered, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({ ok: false, reason: "invalid-signature" });
  });

  it("rejects a token signed by a key that is not in the JWKS", async () => {
    const { jwks, sign } = await createTestSigner();
    const { sign: signWithOtherKey } = await createTestSigner("other-key");
    const token = await signWithOtherKey(validClaims());

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({ ok: false, reason: "invalid-signature" });
  });

  it("rejects an expired JWT", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims({ exp: NOW_SECONDS - 1 }));

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({ ok: false, reason: "expired" });
  });

  it("rejects a JWT that is not yet valid (nbf in the future)", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims({ nbf: NOW_SECONDS + 60 }));

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({ ok: false, reason: "not-yet-valid" });
  });

  it("rejects a JWT with an incorrect issuer", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims({ iss: "https://evil.example.com" }));

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({ ok: false, reason: "wrong-issuer" });
  });

  it("rejects a JWT with an incorrect audience", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims({ aud: "some-other-application-aud" }));

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({ ok: false, reason: "wrong-audience" });
  });

  it("rejects a verified JWT whose email is not in the operator allowlist", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims({ email: "intruder@hivarium.test" }));

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
      authorizedEmails: ["operator@hivarium.test"],
    });

    expect(result).toEqual({ ok: false, reason: "unauthorized-email" });
  });

  it("accepts a verified JWT whose email is in the operator allowlist", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims());

    const result = await verifyAccessJwt(token, {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
      authorizedEmails: ["operator@hivarium.test"],
    });

    expect(result.ok).toBe(true);
  });

  it("reports malformed tokens instead of throwing", async () => {
    const { jwks } = await createTestSigner();

    const result = await verifyAccessJwt("not-a-jwt", {
      jwks,
      issuer: ISSUER,
      audience: AUDIENCE,
      now: NOW,
    });

    expect(result).toEqual({ ok: false, reason: "malformed-token" });
  });
});

describe("authenticateRequest", () => {
  it("rejects a request with no Cf-Access-Jwt-Assertion header", async () => {
    const { jwks } = await createTestSigner();
    const request = new Request("https://example.com/api/me");

    const result = await authenticateRequest(
      request,
      { teamDomain: TEAM_DOMAIN, audience: AUDIENCE, now: NOW },
      { get: async () => jwks }
    );

    expect(result).toEqual({ ok: false, reason: "missing-header" });
  });

  it("rejects a request with an empty Cf-Access-Jwt-Assertion header", async () => {
    const { jwks } = await createTestSigner();
    const request = new Request("https://example.com/api/me", {
      headers: { "Cf-Access-Jwt-Assertion": "   " },
    });

    const result = await authenticateRequest(
      request,
      { teamDomain: TEAM_DOMAIN, audience: AUDIENCE, now: NOW },
      { get: async () => jwks }
    );

    expect(result).toEqual({ ok: false, reason: "missing-header" });
  });

  it("accepts a valid token end to end and returns the operator identity", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims());
    const request = new Request("https://example.com/api/me", {
      headers: { "Cf-Access-Jwt-Assertion": token },
    });

    const result = await authenticateRequest(
      request,
      { teamDomain: TEAM_DOMAIN, audience: AUDIENCE, now: NOW },
      { get: async () => jwks }
    );

    expect(result).toEqual({
      ok: true,
      identity: {
        email: "operator@hivarium.test",
        sub: "user_123",
        name: "Test Operator",
      },
    });
  });

  it("rejects an unauthorized email through the middleware allowlist", async () => {
    const { jwks, sign } = await createTestSigner();
    const token = await sign(validClaims({ email: "intruder@hivarium.test" }));
    const request = new Request("https://example.com/api/me", {
      headers: { "Cf-Access-Jwt-Assertion": token },
    });

    const result = await authenticateRequest(
      request,
      {
        teamDomain: TEAM_DOMAIN,
        audience: AUDIENCE,
        now: NOW,
        authorizedEmails: ["operator@hivarium.test"],
      },
      { get: async () => jwks }
    );

    expect(result).toEqual({ ok: false, reason: "unauthorized-email" });
  });
});

describe("createJwksCache", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("caches the JWKS within the TTL and refreshes after it expires", async () => {
    const { jwks } = await createTestSigner();
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("cloudflareaccess.com/cdn-cgi/access/certs")) {
        return new Response(JSON.stringify(jwks), { status: 200 });
      }
      return new Response("not mocked", { status: 404 });
    });
    vi.stubGlobal("fetch", fetchMock);

    const cache = createJwksCache(undefined, 60_000);
    const first = await cache.get(TEAM_DOMAIN);
    const second = await cache.get(TEAM_DOMAIN);
    expect(first).toEqual(jwks);
    expect(second).toEqual(jwks);
    expect(fetchMock).toHaveBeenCalledTimes(1);

    // Force the TTL to elapse by creating a cache with a zero TTL.
    const shortCache = createJwksCache(undefined, 0);
    await shortCache.get(TEAM_DOMAIN);
    await shortCache.get(TEAM_DOMAIN);
    expect(fetchMock).toHaveBeenCalledTimes(3);
  });

  it("falls back to the stale cached JWKS when a refresh fails", async () => {
    const { jwks } = await createTestSigner();
    let failNext = false;
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("cloudflareaccess.com/cdn-cgi/access/certs")) {
        if (failNext) return new Response("boom", { status: 500 });
        return new Response(JSON.stringify(jwks), { status: 200 });
      }
      return new Response("not mocked", { status: 404 });
    });
    vi.stubGlobal("fetch", fetchMock);

    const cache = createJwksCache(undefined, 0);
    await cache.get(TEAM_DOMAIN);
    failNext = true;
    const stale = await cache.get(TEAM_DOMAIN);
    expect(stale).toEqual(jwks);
  });
});